import '../models/player.dart';
import '../models/team.dart';
import 'id_gen.dart';

/// Equipo de ejemplo ("UTN BA") con 20 jugadores repartidos en partes
/// iguales entre las 5 posiciones (4 jugadores por posición).
Team buildSampleTeamUtnBa() {
  final players = <Player>[
    // Armadores
    Player(
      id: generateId('pl_'),
      firstName: 'Lucas',
      lastName: 'Fernández',
      number: 1,
      position: PlayerPosition.armador,
      heightCm: 180,
      weightKg: 74,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Tomás',
      lastName: 'Gómez',
      number: 7,
      position: PlayerPosition.armador,
      heightCm: 183,
      weightKg: 76,
      dominantHand: DominantHand.izquierda,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Bruno',
      lastName: 'Sosa',
      number: 10,
      position: PlayerPosition.armador,
      heightCm: 179,
      weightKg: 73,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Nicolás',
      lastName: 'Herrera',
      number: 14,
      position: PlayerPosition.armador,
      heightCm: 182,
      weightKg: 75,
      dominantHand: DominantHand.derecha,
    ),

    // Opuestos
    Player(
      id: generateId('pl_'),
      firstName: 'Franco',
      lastName: 'Medina',
      number: 2,
      position: PlayerPosition.opuesto,
      heightCm: 195,
      weightKg: 88,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Agustín',
      lastName: 'Ríos',
      number: 8,
      position: PlayerPosition.opuesto,
      heightCm: 192,
      weightKg: 85,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Ezequiel',
      lastName: 'Torres',
      number: 11,
      position: PlayerPosition.opuesto,
      heightCm: 197,
      weightKg: 90,
      dominantHand: DominantHand.izquierda,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Matías',
      lastName: 'Álvarez',
      number: 17,
      position: PlayerPosition.opuesto,
      heightCm: 193,
      weightKg: 86,
      dominantHand: DominantHand.derecha,
    ),

    // Centrales
    Player(
      id: generateId('pl_'),
      firstName: 'Federico',
      lastName: 'Molina',
      number: 3,
      position: PlayerPosition.central,
      heightCm: 200,
      weightKg: 92,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Joaquín',
      lastName: 'Ibáñez',
      number: 9,
      position: PlayerPosition.central,
      heightCm: 198,
      weightKg: 90,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Ramiro',
      lastName: 'Acosta',
      number: 13,
      position: PlayerPosition.central,
      heightCm: 202,
      weightKg: 94,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Ignacio',
      lastName: 'Paz',
      number: 18,
      position: PlayerPosition.central,
      heightCm: 199,
      weightKg: 91,
      dominantHand: DominantHand.izquierda,
    ),

    // Puntas/Receptores
    Player(
      id: generateId('pl_'),
      firstName: 'Santiago',
      lastName: 'Correa',
      number: 4,
      position: PlayerPosition.puntaReceptor,
      heightCm: 190,
      weightKg: 82,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Valentín',
      lastName: 'Rojas',
      number: 6,
      position: PlayerPosition.puntaReceptor,
      heightCm: 188,
      weightKg: 80,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Emiliano',
      lastName: 'Vega',
      number: 12,
      position: PlayerPosition.puntaReceptor,
      heightCm: 193,
      weightKg: 84,
      dominantHand: DominantHand.izquierda,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Gonzalo',
      lastName: 'Suárez',
      number: 16,
      position: PlayerPosition.puntaReceptor,
      heightCm: 189,
      weightKg: 81,
      dominantHand: DominantHand.derecha,
    ),

    // Líberos
    Player(
      id: generateId('pl_'),
      firstName: 'Julián',
      lastName: 'Núñez',
      number: 5,
      position: PlayerPosition.libero,
      heightCm: 174,
      weightKg: 68,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Maximiliano',
      lastName: 'Ledesma',
      number: 15,
      position: PlayerPosition.libero,
      heightCm: 172,
      weightKg: 66,
      dominantHand: DominantHand.derecha,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Camilo',
      lastName: 'Aguirre',
      number: 19,
      position: PlayerPosition.libero,
      heightCm: 176,
      weightKg: 69,
      dominantHand: DominantHand.izquierda,
    ),
    Player(
      id: generateId('pl_'),
      firstName: 'Benjamín',
      lastName: 'Castro',
      number: 20,
      position: PlayerPosition.libero,
      heightCm: 173,
      weightKg: 67,
      dominantHand: DominantHand.derecha,
    ),
  ];

  return Team(id: generateId('team_'), name: 'UTN BA', players: players);
}
